### PR TITLE
Refactor Directory Structure

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

This Pull Request refactors the Directory Structure and puts the components in a separate `components` sub-directory. Apart from that, File Path Imports have been changed and the changes tested on Node `v14.15.4`. 

Fixes https://github.com/moja-global/contributors_website/issues/7

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Changes Tested on Node `v14.15.4` and NPM `6.14.10`. No breaking change was found during execution.

## Additional Context (Please include any Screenshots/gifs if relevant)

image

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by HarshCasper** [comment]
@Tlazypanda @shubhamkarande13 

Please take a look over it, if you find the change fit :)

**Review by Tlazypanda — APPROVED** [review]
@HarshCasper Lgtm! :tada:

**Comment by HarshCasper** [comment]
Thanks, @Tlazypanda 

It would be great if you can merge the same so that I can work on some other Issues as well :)

**Comment by Tlazypanda** [comment]
@HarshCasper Hadn't merged this earlier because it CD pipeline isn't set at the moment but this an issue can be something you can take up next :)

**Pull request merged**
